import Header from "@/components/Header";
import Main from "@/components/Main";

export const metadata = {
  title: "CRUD App | Home",
  description: "Generated by Youssef Habib",
};

const Home = () => {
  return (
    <div className="container mx-auto">
      <Header />

      <Main />
    </div>
  );
};

export default Home;
